function runAutonomyChecks(){
  const out=[],assert=(v,m)=>{if(!v)throw Error(m)},test=(name,fn)=>{try{transportFixtureB60();fn();out.push({name,ok:true})}catch(e){out.push({name,ok:false,error:e.message})}};
  const charger=()=>({type:'charger',x:180,y:0,r:14,hp:4,speed:0,dead:false,age:0,state:'aim',aim:1,vx:0,vy:0});
  test('B77 steady movement changes the actual committed charge direction',()=>{const e=charger();enemies=[e];for(let i=0;i<21;i++){P.y+=2;updateEnemy(e,.04)}const direct=Math.atan2(P.y-e.y,P.x-e.x);assert(e.b55LaneLocked&&e.b55LaneAngle<direct,'no anticipation');const a=e.b55LaneAngle;P.y-=50;for(let i=0;i<8;i++)updateEnemy(e,.04);assert(e.state==='charge'&&e.b55LaneAngle===a&&Math.abs(Math.atan2(e.vy,e.vx)-a)<1e-8,'lane changed after commitment')});
  test('B77 stationary, dash and pause never manufacture motion knowledge',()=>{const e=charger();for(let i=0;i<21;i++)updateEnemy(e,.04);assert(Math.abs(e.b55LaneAngle-Math.PI)<1e-8,'stationary prediction');e.b55LaneLocked=false;S.dashTime=1;P.y=90;updateEnemy(e,.04);assert(e.b77.time===0,'dash learned');const before=JSON.stringify(e);S.b39Paused=true;updateEnemy(e,.04);assert(JSON.stringify(e)===before,'pause advanced')});
  test('B77 prediction is bounded and cannot change enemy speed',()=>{const e=charger();e.b77={time:1,vx:0,vy:999};lockChargerLaneB55(e);assert(Math.abs(e.b55LaneAngle-Math.atan2(28,180)*-1-Math.PI)<1e-7,'prediction cap');assert(e.speed===0,'speed changed')});
  test('B78 actual escape changes next source selection without forbidding scarce hearts',()=>{P.pipX=0;P.pipY=0;S.pipDetectRange=200;const near=makeHeartSourceB74(1,20,0),other=makeHeartSourceB74(1,-45,0);heartBits=[near,other];assert(nextHeartSourceB74()===near,'baseline preference');const f=feelingsB76();f.trip={time:2,maxDistance:150,danger:1,rough:false};f.motives.concern=1;transportB60().cargo=[makeHeartSourceB74(1,0,0)];decidePipB76();assert(f.intent==='shelter'&&roughPatchesB78().length===1,'escape not recorded');decidePipB76();assert(roughPatchesB78().length===1,'duplicate patch');transportB60().cargo=[];S.pipState='collect';assert(nextHeartSourceB74()===other,'same route despite memory');heartBits=[near];assert(nextHeartSourceB74()===near,'memory made source unavailable')});
  test('B78 memories are bounded, fade only in gameplay, and clear with stage or reset',()=>{for(let i=0;i<6;i++)rememberPatchB78(i*120,0);assert(roughPatchesB78().length===3,'unbounded memory');const before=JSON.stringify(roughPatchesB78());S.b39Paused=true;updatePipTransportB60(.04);assert(JSON.stringify(roughPatchesB78())===before,'paused memory faded');S.b39Paused=false;for(let i=0;i<601;i++)observePipB76(.04);assert(!roughPatchesB78().length,'memory permanent');rememberPatchB78(0,0);openStageUpgrade();assert(!roughPatchesB78().length,'stage carried location');rememberPatchB78(0,0);reset();assert(!roughPatchesB78().length,'run carried location')});
  test('B79 distant missed charges delay the next aim while close passes do not',()=>{const e=charger();e.state='charge';e.charge=.01;e.vx=340;enemies=[e];updateEnemy(e,.04);assert(e.state==='aim'&&e.b79.recover===.18,'miss did not recover');const aim=e.aim;updateEnemy(e,.04);assert(Math.abs(e.aim-aim)<1e-8&&e.b79.recover<.18,'next aim not delayed');const close=charger();close.x=50;close.state='charge';close.charge=.01;close.vx=340;updateEnemy(close,.04);assert(close.b79.recover===0&&close.b79.misses===0,'close pass punished')});
  test('B79 repeated misses are bounded and pause preserves recovery',()=>{const e=charger();e.b79={misses:2,nearest:Infinity,recover:0};e.state='charge';e.charge=.01;e.vx=340;updateEnemy(e,.04);assert(e.b79.recover===.36,'unbounded reset');const before=JSON.stringify(e);S.b39Paused=true;updateEnemy(e,.04);assert(JSON.stringify(e)===before,'paused recovery advanced');S.b39Paused=false;for(let i=0;i<10;i++)updateEnemy(e,.04);assert(e.b79.recover===0&&e.state==='aim','recovery never ended')});
  test('B79 recovering chargers remain vulnerable to ordinary dash contact',()=>{const e=charger();e.x=0;e.b79={misses:1,nearest:Infinity,recover:.18};enemies=[e];S.dashTime=.2;updateEnemy(e,.04);assert(e.dead,'recovery skipped dash collision')});
  return out;
}
