qaButtonB59('Autonomous behavior checks',()=>{$('qaResults').textContent=runAutonomyChecks().map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.error?': '+r.error:''}`).join('\n');qaFrozenB59=true});
function reunionSceneB83(trusted){transportFixtureB60();S.shields=3;P.pipX=P.x=0;P.pipY=P.y=0;S.pipLove=3;feelingsB76().trust=trusted?.8:.5;enemies=[{type:'chaser',x:0,y:90,r:12,hp:20,dead:false,age:0,speed:0},{type:'charger',x:110,y:0,r:14,hp:20,dead:false,age:0,state:'charge',vx:-340,vy:0,charge:.52}];shots=[];reunitePipB60();for(const s of shots){s.x+=s.vx*.1;s.y+=s.vy*.1}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`${trusted?'Trusted':'Fresh'} Pip: three reunion shots ${shots[1].vx>530?'toward charging threat':'toward nearest enemy'}`}
qaButtonB59('B83 fresh reunion',()=>reunionSceneB83(false));
qaButtonB59('B83 trusted reunion',()=>reunionSceneB83(true));
qaButtonB59('B77 committed prediction',()=>{transportFixtureB60();S.shields=3;const e={type:'charger',x:130,y:0,r:14,hp:4,speed:0,dead:false,age:0,state:'aim',aim:1,vx:0,vy:0};enemies=[e];for(let i=0;i<21;i++){P.y+=2;updateEnemy(e,.04)}qaFrozenB59=true;qaStatusB59()});
function patchSceneB78(remember){transportFixtureB60();P.pipX=0;S.shields=3;S.pipDetectRange=200;heartBits=[makeHeartSourceB74(3,100,0,40),makeHeartSourceB74(3,-125,0,40)];if(remember)rememberPatchB78(100,0);S.pipTarget=nextHeartSourceB74();qaFrozenB59=true;qaUpdateB59(.04);qaStatusB59();$('qaResults').textContent=`Chosen patch: ${S.pipTarget?.x}. Remembered patches: ${roughPatchesB78().length}`}
qaButtonB59('B78 fresh patch',()=>patchSceneB78(false));
qaButtonB59('B78 remembered patch',()=>patchSceneB78(true));
qaButtonB59('B79 missed charge',()=>{transportFixtureB60();S.shields=3;const e={type:'charger',x:100,y:0,r:14,hp:4,speed:0,dead:false,age:0,state:'charge',charge:.01,aim:1,vx:340,vy:0};enemies=[e];updateEnemy(e,.04);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Reset: ${e.b79.recover.toFixed(2)}s. Aim: ${e.aim.toFixed(2)}s`});
qaButtonB59('B80 danger replan',()=>{transportFixtureB60();P.pipX=0;P.pipY=0;S.shields=3;S.pipDetectRange=240;const threatened=makeHeartSourceB74(1,100,0),safe=makeHeartSourceB74(1,-100,0);heartBits=[threatened,safe];enemies=[{type:'drifter',x:100,y:0,r:12,hp:2,dead:false,age:0,vx:0,vy:0}];S.pipState='collect';S.pipTarget=threatened;updatePipTransportB60(.04);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Target: ${Math.round(S.pipTarget.x)}. Replans: ${replanStateB80().count}. Cue: ${replanStateB80().cue.toFixed(2)}s`});
qaButtonB59('B82 enemy rotations',()=>{const checks=runSurvivalChecksB63().filter(r=>r.name.startsWith('B82'));transportFixtureB60();S.stage=7;const rows=checks.map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.error?': '+r.error:''}`);for(let wave=1;wave<=3;wave++){S.stageWaveCount=wave;const roster=enemyRosterB82(),counts={chaser:0,core:0,charger:0};for(let i=0;i<1000;i++)counts[rosterEnemyB82(roster,i/1000)]++;rows.push(`${wave} ${roster.name} · cap ${enemyCap()} · ${counts.chaser}/${counts.core}/${counts.charger}`)}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=rows.join('\n')});
function escalationSceneB84(hold){transportFixtureB60();S.shields=3;S.bossActive=true;S.bossCount=0;S.bossMidPraise=false;S.waveState='boss';const e={type:'boss',bossKey:1,x:P.x+180,y:P.y,r:30,hp:51,maxHp:100,dead:false,age:0,flash:0};enemies=[e];updateEnemy(e,.04);hitEnemy(e,3);const atThreshold=S.bossMidPraise;let frames=0;if(!hold){while(frames<400&&!S.bossMidPraise){updateEnemy(e,.04);frames++}}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`HP ${e.hp}/${e.maxHp} · phase two ${e.b59.second} · cue at threshold ${atThreshold} · cue now ${S.bossMidPraise}${hold?'':` after ${frames} frames`}`}
qaButtonB59('B84 cue at threshold',()=>escalationSceneB84(true));
qaButtonB59('B84 cue at escalation',()=>escalationSceneB84(false));
function coverSceneB85(shotFirst){transportFixtureB60();P.x=P.y=P.vx=P.vy=0;P.pipX=8;P.pipY=0;S.pipState='orbit';S.shields=1;S.invuln=0;S.pipCompassion=2;S.waveState='active';partnershipB59().coverCd=0;enemyShots=[{x:60,y:0,vx:-600,vy:0,r:5,life:3}];enemies=shotFirst?[]:[{type:'chaser',x:0,y:40,r:12,dead:false,vx:0,vy:-60,hp:3,age:0}];const t=incomingThreatB59();partnershipB59().coverThreat=t;qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Threat ${t?`${Math.round(t.x)},${Math.round(t.y)}`:'none'} · ${t&&t.x===60?'imminent shot':'body'} · bodies ${enemies.length}`}
qaButtonB59('B85 shot only',()=>coverSceneB85(true));
qaButtonB59('B85 shot vs later body',()=>coverSceneB85(false));
